variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

stages:
  - build
  - deploy

build:
  stage: build
  interruptible: true
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - |-
      cat <<-EOF > /kaniko/.docker/config.json
      {
        "auths": {
          "$CI_REGISTRY": {
            "username": "$CI_REGISTRY_USER",
            "password": "$CI_REGISTRY_PASSWORD"
          }
        }
      }
      EOF
  script:
    - |-
      /kaniko/executor \
        --context $CI_PROJECT_DIR \
        --dockerfile $CI_PROJECT_DIR/Dockerfile \
        --destination $IMAGE_TAG

deploy:
  stage: deploy
  interruptible: true
  image:
    name: "bitnami/kubectl:latest"
    entrypoint: [""]
  script:
    - cat k8s.yaml | sed "s#$CI_REGISTRY_IMAGE#$IMAGE_TAG#g" | kubectl apply -f -
